### ISSUE TITLE
portmaster build: failure: unknown option -- D

### ISSUE THREAD

**Issue by SB211** [trombik/xtensa-esp32-elf#46]
By pulling the lastest repository via git pull, building as part of the FreeBSD ports tree fails due to some overlapping environment issues (I do not know the exact cause, but the solution is very simple and involves only the Makefile by replacing ${SETENV} by ${SETENVI} where code is build via gmake).
The issue does not occur when using "make all" in the port's folder or via poudriere - only portmaster fails. But the solution for this works in all building schemes.

**Comment by trombik** [comment]
Provide the log and the output of `env`.

**Comment by SB211** [comment]
Sorry for the late response.
For the SETENVI issue, please be referred to /usr/ports/CHANGES:

[...]
20240229:
AUTHOR: tijl@FreeBSD.org
...

Without those changes, the port builds with poudriere, but will fail using portmaster (at least in my case). I made some changes to compile at least FLAVOR=idf51 (the others fail at several points on recent CURRENT and recent 14-STABLE, poudriere with clean environment as well as portmaster). 
I "polluted" my git's Makefile with some stupid attempts incorporating idf52, so I'd be happy if I could contact you via your "Maintainers Email" provided in the Makefile - if this is an adequate way? Also willing to provide log file of the failing FLAVOR=idf44 attempts ...

**Comment by SB211** [comment]
Startover with most recent xtensa-esp-elf port
