### ISSUE TITLE
buildtime  excessive 

### ISSUE THREAD

**Issue by SB211** [trombik/xtensa-esp32-elf#50]
When building the port devel/xtensa-esp32-elf buildprocess consumes excessive time running git:

[...]
INFO  :: *** Generating menu/choice selections
INFO  :: Generating arch.in (choice)
INFO  :: Generating kernel.in (choice)
INFO  :: Generating cc.in (choice)
INFO  :: Generating binutils.in (choice)
INFO  :: Generating libc.in (choice)
INFO  :: Generating debug.in (menu)
INFO  :: Generating comp_tools.in (menu)
INFO  :: Generating comp_libs.in (menu)
INFO  :: *** Gathering the list of data files to install
INFO  :: *** Running autoreconf
load: 1.46  cmd: git 18819 [running] 22.89r 22.80u 0.07s 93% 414928k
make: Working in: /usr/ports/devel/xtensa-esp32-elf
[...]

The above message (Ctrl-t) has been taken after almost half an hour build time. I can't figure out at which point the build process needs git for that much time downloading/updating files ...

Can this be accelerated somehow? Testing the port results in a nightmare having to wait that long ...

**Comment by trombik** [comment]
The build process is a bit funny. It assumes unrestricted Internet access, which is a big "No" in the ports build process. Please use `poudriere`, which ensures that the build is isolated from the Internet. If you still have te issue after that, please open another issue.

Thanks.
