### ISSUE TITLE
ESP-IDF 5.3 is out

### ISSUE THREAD

**Issue by SB211** [trombik/xtensa-esp32-elf#55]
I'd like to point to the existence of the newly created ESP-IDF tag 5.3. Trying to simply "copy and paste" the port's definition for building also for the IDF 5.3 version (FLAVOR=idf53),  I'm not sure whether the new IDF has any differences compared to recent 5.2.2 in the binary dependencies.

Could we have official support for ESP-IDF 5.3 through this repository? This seems interesting also for new ESP32 chips.

Thank you very much in advance.

**Comment by trombik** [comment]
As the build config has changed, the porting takes time. No ETA.

Also, please do NOT report any issues to the upstream unless you know what you are doing. Report issues here.
