### ISSUE TITLE
FreeBSD: ports-mgmt/portmaster issues 

### ISSUE THREAD

**Issue by SB211** [trombik/xtensa-esp32-elf#65]
Host running FreeBSD CURRENT (FreeBSD 15.0-CURRENT #8 main-n272126-7a6309fdc794: Sat Sep  7 07:07:14 CEST 2024 amd64), official ports tree up to date.

Trying to build devel/xtensa-esp-elf via

portmaster devel/xtensa-esp-elf@idf53

results in a bunch of errors, at a first glance not harmful for the subsequent build:

[...]
=> SHA256 Checksum OK for rust-lang-libc-0.2.147_GH0.tar.gz.
make: "/usr/ports/Mk/bsd.sites.mk" line 361: while evaluating variable "DISTNAME_DEFAULT" with value "xtensa-esp32-elf-xtensa-esp32-elf-${DISTVERSIONPREFIX}${ESPRESSIF_VERSION:S-esp---:S-crosstool-ng---:S-r-.r-:S----:S-patch-.p-:S-_--}${DISTVERSIONSUFFIX}_GH0": while evaluating variable "ESPRESSIF_VERSION" with value "": Unknown modifier "-"
        in /usr/ports/Mk/bsd.port.mk:2238
        in /usr/share/mk/bsd.port.mk:27
        in /usr/ports/devel/xtensa-esp32-elf/Makefile:381
make: "/usr/ports/Mk/bsd.sites.mk" line 361: while evaluating variable "DISTNAME_DEFAULT" with value "xtensa-esp32-elf-xtensa-esp32-elf-${DISTVERSIONPREFIX}${ESPRESSIF_VERSION:S-esp---:S-crosstool-ng---:S-r-.r-:S----:S-patch-.p-:S-_--}${DISTVERSIONSUFFIX}_GH0": while evaluating variable "ESPRESSIF_VERSION" with value "": Unknown modifier "--"
        in /usr/ports/Mk/bsd.port.mk:2238
        in /usr/share/mk/bsd.port.mk:27
        in /usr/ports/devel/xtensa-esp32-elf/Makefile:381
make: "/usr/ports/Mk/bsd.sites.mk" line 361: while evaluating variable "DISTNAME_DEFAULT" with value "xtensa-esp32-elf-xtensa-esp32-elf-${DISTVERSIONPREFIX}${ESPRESSIF_VERSION:S-esp---:S-crosstool-ng---:S-r-.r-:S----:S-patch-.p-:S-_--}${DISTVERSIONSUFFIX}_GH0": while evaluating variable "ESPRESSIF_VERSION" with value "": Unknown modifier "-"
        in /usr/ports/Mk/bsd.port.mk:2238
        in /usr/share/mk/bsd.port.mk:27
        in /usr/ports/devel/xtensa-esp32-elf/Makefile:381
make: "/usr/ports/Mk/bsd.sites.mk" line 1130: while evaluating variable "MASTER_SITES_SUBDIRS" with value "APACHE_COMMONS_BINARIES:${PORTNAME:S,commons-,,}  APACHE_COMMONS_SOURCE:${PORTNAME:S,commons-,,}  APACHE_JAKARTA:${PORTNAME:S,-,/,}/source  BERLIOS:${PORTNAME:tl}.berlios  CRATESIO:${PORTNAME}/${DISTVERSIONFULL}  DEBIAN:pool/main/${PORTNAME:C/^((lib)?.).*$/\1/}/${PORTNAME}  FARSIGHT:${PORTNAME}  FESTIVAL:${PORTVERSION}  GCC:releases/${DISTNAME}  GENTOO:distfiles  GIMP:${PORTNAME}/${PORTVERSION:R}/  GITHUB:${GH_ACCOUNT}/${GH_PROJECT}/tar.gz/${GH_TAGNAME}?dummy=/  GITHUB_CLOUD:${GH_ACCOUNT}/${GH_PROJECT}/  GNOME:sources/${PORTNAME}/${PORTVERSION:C/^([0-9]+\.[0-9]+).*/\1/}  GNU:${PORTNAME}  GNUPG:${PORTNAME}  GNU_ALPHA:${PORTNAME}  LIBREOFFICE_DEV:${PORTNAME}  MATE:${PORTVERSION:C/^([0-9]+\.[0-9]+).*/\1/}  MOZDEV:${PORTNAME:tl}  NETLIB:${PORTNAME}  PERL_CPAN:${PORTNAME:C/-.*//}  PYPI:source/${DISTNAME:C/(.).*/\1/}/${DISTNAME:S/-${DISTVERSIONFULL}$//}  QT:archive/qt/${PORTVERSION:R}  SAMBA:${PORTNAME}  SAVANNAH:${PORTNAME:tl}  SOURCEFORGE:${PORTNAME:tl}/${PORTNAME:tl}/${PORTVERSION}  XFCE:xfce": while evaluating variable "DISTNAME" with value "xtensa-esp32-elf-xtensa-esp32-elf-${DISTVERSIONPREFIX}${ESPRESSIF_VERSION:S-esp---:S-crosstool-ng---:S-r-.r-:S----:S-patch-.p-:S-_--}${DISTVERSIONSUFFIX}_GH0": while evaluating variable "ESPRESSIF_VERSION" with value "": Unknown modifier "-"
        in .for loop from /usr/ports/Mk/bsd.sites.mk:1109 with _site__ = GH
        in /usr/ports/Mk/bsd.port.mk:2238
        in /usr/share/mk/bsd.port.mk:27
        in /usr/ports/devel/xtensa-esp32-elf/Makefile:381
make: "/usr/ports/Mk/bsd.sites.mk" line 1130: while evaluating variable "MASTER_SITES_SUBDIRS" with value "APACHE_COMMONS_BINARIES:${PORTNAME:S,commons-,,}  APACHE_COMMONS_SOURCE:${PORTNAME:S,commons-,,}  APACHE_JAKARTA:${PORTNAME:S,-,/,}/source  BERLIOS:${PORTNAME:tl}.berlios  CRATESIO:${PORTNAME}/${DISTVERSIONFULL}  DEBIAN:pool/main/${PORTNAME:C/^((lib)?.).*$/\1/}/${PORTNAME}  FARSIGHT:${PORTNAME}  FESTIVAL:${PORTVERSION}  GCC:releases/${DISTNAME}  GENTOO:distfiles  GIMP:${PORTNAME}/${PORTVERSION:R}/  GITHUB:${GH_ACCOUNT}/${GH_PROJECT}/tar.gz/${GH_TAGNAME}?dummy=/  GITHUB_CLOUD:${GH_ACCOUNT}/${GH_PROJECT}/  GNOME:sources/${PORTNAME}/${PORTVERSION:C/^([0-9]+\.[0-9]+).*/\1/}  GNU:${PORTNAME}  GNUPG:${PORTNAME}  GNU_ALPHA:${PORTNAME}  LIBREOFFICE_DEV:${PORTNAME}  MATE:${PORTVERSION:C/^([0-9]+\.[0-9]+).*/\1/}  MOZDEV:${PORTNAME:tl}  NETLIB:${PORTNAME}  PERL_CPAN:${PORTNAME:C/-.*//}  PYPI:source/${DISTNAME:C/(.).*/\1/}/${DISTNAME:S/-${DISTVERSIONFULL}$//}  QT:archive/qt/${PORTVERSION:R}  SAMBA:${PORTNAME}  SAVANNAH:${PORTNAME:tl}  SOURCEFORGE:${PORTNAME:tl}/${PORTNAME:tl}/${PORTVERSION}  XFCE:xfce": while evaluating variable "DISTNAME" with value "xtensa-esp32-elf-xtensa-esp32-elf-${DISTVERSIONPREFIX}${ESPRESSIF_VERSION:S-esp---:S-crosstool-ng---:S-r-.r-:S----:S-patch-.p-:S-_--}${DISTVERSIONSUFFIX}_GH0": while evaluating variable "ESPRESSIF_VERSION" with value "": Unknown modifier "--"
[...]

**Comment by trombik** [comment]
Hi,

Please follow my instructions in other issues you reported. I'm trying to help you, but you aren't. Or, you will be blocked.

**Comment by SB211** [comment]
> Hi,
> 
> Please follow my instructions in other issues you reported. I'm trying to help you, but you aren't. Or, you will be blocked.

Thank you for responding and sorry for bothering you again in the mastter of testing.

Why sending tons of logs derived from a vanilla recent FBSD with mutually sensitive data of the host, when the problem described can be easily reproduced, giving the opprotunity having log first hand? 

What log do you need and where to put it?

With poudriere, there wasn't any issue with the previous incanation of your port, also "make all" followed by "portmaster -C" worked well. Usage of portmaster as the solitair tool does have issues with a new approach refered to in /usr/ports/CHANGELOG regarding ${SETNEVI}.
I tried to fix several ports on FreeBSD, but some maintainer consider ports-mgmt/portmaster not as standard tool.

All right, before getting deeper into a mess and being blocked, we should consider the issue "solved", I try to solve the problem with portmaster as a portmaster-only-issue.
Kind regards, oh
